#!/bin/bash

# Fungsi untuk menampilkan daftar perintah yang tersedia dan penggunaannya
helpme() {
  case "$1" in
    "docker")
      echo -e "\e[1;34m== Manajemen Docker dan Podman ==\e[0m"
      echo -e "  \e[1;32mdstop\e[0m    - Menghentikan Docker"
      echo -e "             \e[1;30mContoh: dstop\e[0m"
      echo -e "  \e[1;32mpstop\e[0m    - Menghentikan Podman"
      echo -e "             \e[1;30mContoh: pstop\e[0m"
      echo -e "  \e[1;32mdstart\e[0m   - Memulai Docker"
      echo -e "             \e[1;30mContoh: dstart\e[0m"
      echo -e "  \e[1;32mpstart\e[0m   - Memulai Podman"
      echo -e "             \e[1;30mContoh: pstart\e[0m"
      echo -e "  \e[1;32mdstat\e[0m    - Mengecek status Docker"
      echo -e "             \e[1;30mContoh: dstat\e[0m"
      echo -e "  \e[1;32mpstat\e[0m    - Mengecek status Podman"
      echo -e "             \e[1;30mContoh: pstat\e[0m"
      ;;
    "wifi")
      echo -e "\e[1;34m== Manajemen Jaringan ==\e[0m"
      echo -e "  \e[1;32mstwifi\e[0m   - Mengecek status NetworkManager"
      echo -e "             \e[1;30mContoh: stwifi\e[0m"
      echo -e "  \e[1;32mstartwifi\e[0m- Memulai NetworkManager"
      echo -e "             \e[1;30mContoh: startwifi\e[0m"
      echo -e "  \e[1;32mlwifi\e[0m    - Menampilkan daftar jaringan WiFi yang tersedia"
      echo -e "             \e[1;30mContoh: lwifi\e[0m"
      echo -e "  \e[1;32mlswifi\e[0m   - Memindai ulang jaringan WiFi"
      echo -e "             \e[1;30mContoh: lswifi\e[0m"
      echo -e "  \e[1;32mcwifi\e[0m    - Skrip kustom untuk manajemen WiFi"
      echo -e "             \e[1;30mContoh: cwifi\e[0m"
      echo -e "  \e[1;32mrwifi\e[0m    - Memulai ulang NetworkManager"
      echo -e "             \e[1;30mContoh: rwifi\e[0m"
      echo -e "  \e[1;32mofwifi\e[0m   - Mematikan WiFi"
      echo -e "             \e[1;30mContoh: ofwifi\e[0m"
      echo -e "  \e[1;32monwifi\e[0m   - Menyalakan WiFi"
      echo -e "             \e[1;30mContoh: onwifi\e[0m"
      echo -e "  \e[1;32mswifi\e[0m    - Menghubungkan ke jaringan WiFi dengan SSID dan password"
      echo -e "             \e[1;30mContoh: swifi <SSID> <PASSWORD>\e[0m"
      ;;
    "files")
      echo -e "\e[1;34m== Manajemen Izin File ==\e[0m"
      echo -e "  \e[1;32mmod\e[0m      - Membuat file di direktori saat ini dapat dieksekusi"
      echo -e "             \e[1;30mContoh: mod\e[0m"
      echo -e "  \e[1;32mmx\e[0m       - Membuat semua file dapat dieksekusi"
      echo -e "             \e[1;30mContoh: mx\e[0m"
      echo -e "  \e[1;32m000, 644, 666, 755, 777\e[0m - Mengatur izin file"
      echo -e "             \e[1;30mContoh: 755 (mengatur izin direktori/file ke 755)\e[0m"
      ;;
    "misc")
      echo -e "\e[1;34m== Lain-lain ==\e[0m"
      echo -e "  \e[1;32mhapus\e[0m    - Menghapus file dan direktori dengan paksa"
      echo -e "             \e[1;30mContoh: hapus <file_direktori>\e[0m"
      echo -e "  \e[1;32mscursor\e[0m  - Menjalankan cursor.appimage dengan sudo"
      echo -e "             \e[1;30mContoh: scursor\e[0m"
      ;;
    "custom")
      echo -e "\e[1;34m== Fungsi Kustom ==\e[0m"
      echo -e "  \e[1;32mmkdirg\e[0m   - Membuat direktori dan masuk ke dalamnya"
      echo -e "             \e[1;30mContoh: mkdirg <nama_direktori>\e[0m"
      echo -e "  \e[1;32mgupp\e[0m     - Menambahkan semua perubahan, commit dengan pesan, dan push ke repository"
      echo -e "             \e[1;30mContoh: gupp <pesan_commit>\e[0m"
      echo -e "  \e[1;32mxampp_control\e[0m - Mengontrol layanan XAMPP (start, stop, restart, status)"
      echo -e "                  \e[1;30mContoh: xampp_control <start|stop|restart|status>\e[0m"
      echo -e "  \e[1;32mcpg\e[0m      - Menyalin file dengan timestamp jika tujuan sudah ada, kemudian masuk ke tujuan"
      echo -e "             \e[1;30mContoh: cpg <file_sumber> <direktori_tujuan>\e[0m"
      echo -e "  \e[1;32mmvg\e[0m      - Memindahkan file dengan timestamp jika tujuan sudah ada, kemudian masuk ke tujuan"
      echo -e "             \e[1;30mContoh: mvg <file_sumber> <direktori_tujuan>\e[0m"
      echo -e "  \e[1;32mcpwd\e[0m     - Menyalin direktori saat ini ke tujuan yang ditentukan, atau menyalin path saat ini ke clipboard"
      echo -e "             \e[1;30mContoh: cpwd [direktori_tujuan]\e[0m"
      echo -e "  \e[1;32mswifi\e[0m    - Menghubungkan ke jaringan WiFi dengan SSID dan password"
      echo -e "             \e[1;30mContoh: swifi <SSID> <PASSWORD>\e[0m"
      echo -e "  \e[1;32mvs\e[0m       - Navigasi ke direktori dan membukanya di VS Code"
      echo -e "             \e[1;30mContoh: vs <direktori>\e[0m"
      echo -e "  \e[1;32mee\e[0m       - Navigasi ke direktori dan membukanya di pengelola file Caja"
      echo -e "             \e[1;30mContoh: ee <direktori>\e[0m"
      echo -e "  \e[1;32mweb\e[0m      - Membuka direktori saat ini di browser web menunjuk ke localhost"
      echo -e "             \e[1;30mContoh: web\e[0m"
      echo -e "  \e[1;32mlocal\e[0m    - Membuka phpMyAdmin di browser web menunjuk ke localhost"
      echo -e "             \e[1;30mContoh: local\e[0m"
      echo -e "  \e[1;32mgrr\e[0m      - Membuka halaman repository GitHub di browser web"
      echo -e "             \e[1;30mContoh: grr\e[0m"
      echo -e "  \e[1;32mgn\e[0m       - Membuka halaman pembuatan repository baru GitHub di browser web"
      echo -e "             \e[1;30mContoh: gn\e[0m"
      echo -e "  \e[1;32mhp\e[0m       - Memulai scrcpy dengan pengaturan yang ditentukan"
      echo -e "             \e[1;30mContoh: hp\e[0m"
      echo -e "  \e[1;32mcursor\e[0m   - Menjalankan cursor.appimage dari direktori yang ditentukan"
      echo -e "             \e[1;30mContoh: cursor <direktori>\e[0m"
      echo -e "  \e[1;32mcdf\e[0m      - Mengganti direktori menggunakan fzf untuk memilih dari subdirektori"
      echo -e "             \e[1;30mContoh: cdf\e[0m"
      ;;
    *)
      echo -e "\e[1;34m== Perintah yang tersedia dan penggunaannya ==\e[0m"
      echo ""
      echo -e "\e[1;33m== Listing Direktori ==\e[0m"
      echo -e "  \e[1;32mls\e[0m      - Menampilkan daftar direktori menggunakan exa"
      echo -e "  \e[1;32mll\e[0m      - Menampilkan daftar direktori dengan ikon menggunakan exa"
      echo -e "  \e[1;32mtree\e[0m    - Menampilkan struktur direktori menggunakan exa"
      echo ""
      echo -e "\e[1;33m== Navigasi dan Manajemen Direktori ==\e[0m"
      echo -e "  \e[1;32mc\e[0m       - Membersihkan layar terminal"
      echo -e "  \e[1;32me\e[0m       - Membuka direktori saat ini di pengelola file Caja"
      echo -e "  \e[1;32mwww\e[0m     - Navigasi ke direktori root server web"
      echo -e "  \e[1;32mg\e[0m       - Navigasi ke direktori GitHub"
      echo -e "  \e[1;32mhome, h\e[0m - Navigasi ke direktori home"
      echo -e "  \e[1;32mehtdoc\e[0m  - Membuka direktori root server web di Caja"
      echo -e "  \e[1;32mhtdoc\e[0m   - Navigasi ke direktori root server web"
      echo ""
      echo -e "\e[1;33m== Editor Teks dan IDE ==\e[0m"
      echo -e "  \e[1;32mvim\e[0m     - Menggunakan Neovim sebagai editor default"
      echo -e "  \e[1;32mv\e[0m       - Membuka direktori saat ini di VS Code"
      echo -e "  \e[1;32madd\e[0m     - Mengedit pintasan aplikasi lokal di VS Code"
      echo -e "  \e[1;32mprofile\e[0m - Membuka konfigurasi Zsh di VS Code"
      echo -e "  \e[1;32mscode\e[0m   - Membuka VS Code dengan izin sudo"
      echo ""
      echo -e "\e[1;33m== Manajemen Konfigurasi Zsh ==\e[0m"
      echo -e "  \e[1;32mrprofile\e[0m - Memuat ulang konfigurasi Zsh"
      echo ""
      echo -e "\e[1;33m== Izin File ==\e[0m"
      echo -e "  \e[1;32mmod\e[0m      - Membuat file di direktori saat ini dapat dieksekusi"
      echo -e "  \e[1;32mmx\e[0m       - Membuat semua file dapat dieksekusi"
      echo -e "  \e[1;32m000, 644, 666, 755, 777\e[0m - Mengatur izin file"
      echo ""
      echo -e "\e[1;33m== Lain-lain ==\e[0m"
      echo -e "  \e[1;32mhapus\e[0m    - Menghapus file dan direktori dengan paksa"
      echo -e "  \e[1;32mscursor\e[0m  - Menjalankan cursor.appimage dengan sudo"
      echo ""
      echo -e "\e[1;33m== Fungsi Kustom ==\e[0m"
      echo -e "  \e[1;32mmkdirg\e[0m   - Membuat direktori dan masuk ke dalamnya"
      echo -e "             \e[1;30mContoh: mkdirg <nama_direktori>\e[0m"
      echo -e "  \e[1;32mgupp\e[0m     - Menambahkan semua perubahan, commit dengan pesan, dan push ke repository"
      echo -e "             \e[1;30mContoh: gupp <pesan_commit>\e[0m"
      echo -e "  \e[1;32mxampp_control\e[0m - Mengontrol layanan XAMPP (start, stop, restart, status)"
      echo -e "                  \e[1;30mContoh: xampp_control <start|stop|restart|status>\e[0m"
      echo -e "  \e[1;32mcpg\e[0m      - Menyalin file dengan timestamp jika tujuan sudah ada, kemudian masuk ke tujuan"
      echo -e "             \e[1;30mContoh: cpg <file_sumber> <direktori_tujuan>\e[0m"
      echo -e "  \e[1;32mmvg\e[0m      - Memindahkan file dengan timestamp jika tujuan sudah ada, kemudian masuk ke tujuan"
      echo -e "             \e[1;30mContoh: mvg <file_sumber> <direktori_tujuan>\e[0m"
      echo -e "  \e[1;32mcpwd\e[0m     - Menyalin direktori saat ini ke tujuan yang ditentukan, atau menyalin path saat ini ke clipboard"
      echo -e "             \e[1;30mContoh: cpwd [direktori_tujuan]\e[0m"
      echo -e "  \e[1;32mswifi\e[0m    - Menghubungkan ke jaringan WiFi dengan SSID dan password"
      echo -e "             \e[1;30mContoh: swifi <SSID> <PASSWORD>\e[0m"
      echo -e "  \e[1;32mvs\e[0m       - Navigasi ke direktori dan membukanya di VS Code"
      echo -e "             \e[1;30mContoh: vs <direktori>\e[0m"
      echo -e "  \e[1;32mee\e[0m       - Navigasi ke direktori dan membukanya di pengelola file Caja"
      echo -e "             \e[1;30mContoh: ee <direktori>\e[0m"
      echo -e "  \e[1;32mweb\e[0m      - Membuka direktori saat ini di browser web menunjuk ke localhost"
      echo -e "             \e[1;30mContoh: web\e[0m"
      echo -e "  \e[1;32mlocal\e[0m    - Membuka phpMyAdmin di browser web menunjuk ke localhost"
      echo -e "             \e[1;30mContoh: local\e[0m"
      echo -e "  \e[1;32mgrr\e[0m      - Membuka halaman repository GitHub di browser web"
      echo -e "             \e[1;30mContoh: grr\e[0m"
      echo -e "  \e[1;32mgn\e[0m       - Membuka halaman pembuatan repository baru GitHub di browser web"
      echo -e "             \e[1;30mContoh: gn\e[0m"
      echo -e "  \e[1;32mhp\e[0m       - Memulai scrcpy dengan pengaturan yang ditentukan"
      echo -e "             \e[1;30mContoh: hp\e[0m"
      echo -e "  \e[1;32mcursor\e[0m   - Menjalankan cursor.appimage dari direktori yang ditentukan"
      echo -e "             \e[1;30mContoh: cursor <direktori>\e[0m"
      echo -e "  \e[1;32mcdf\e[0m      - Mengganti direktori menggunakan fzf untuk memilih dari subdirektori"
      echo -e "             \e[1;30mContoh: cdf\e[0m"
      ;;
  esac
}

helpme "$1"
